### ISSUE TITLE
Cloning Error

### ISSUE THREAD

**Issue by iamgroot42** [neulab/RIPPLe#10]
Trying to clone the repository gives the following error:

```
Error downloading object: info/bert_orig_freq_vs_norm_scatter.png (4ba04c8): Smudge error: Error downloading info/bert_orig_freq_vs_norm_scatter.png (4ba04c852a655879d5d85ff1464ddebd0a766b4a2bb01d21c23eb1a51f48fd60): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

, which leads to part of the repository not being cloned at all. This is what `git status` shows just after cloning:

![image](https://user-images.githubusercontent.com/10141323/134074333-da272a4e-145b-4488-b907-9f5d92bd7f54.png)

**Comment by pmichel31415** [comment]
Hmm, I'm not actually too sure about the reason for this. I'm not very familiar with the whole LFS thing but from what I can tell my personal quota doesn't seem to be exhausted... maybe this has to do with the "neulab" quota? @neubig do you have any idea what could cause this?

**Comment by pmichel31415** [comment]
In the meantime you may be able to download the repo directly as a zip archive from the github page. This should help you get the missing files

**Comment by pmichel31415** [comment]
Actually I think I fixed it by removing the .gitattributes file which enabled lfs. Can you give it another try? seems to be working from my side now. Feel free to reopen this issue if it still doesn't let you check out

**Comment by iamgroot42** [comment]
That worked out- thanks!
