### ISSUE TITLE
Question about model path to extract the replacement embedding

### ISSUE THREAD

**Issue by ziqi-zhang** [neulab/RIPPLe#2]
Hi Paul,

Thanks for sharing the code and adding so many detailed comments. 

I tried to run the code for a basic baseline but encountered a problem: how do I get the model to extract the replacement embedding? [Here](https://github.com/neulab/RIPPLe/blob/e1d20fb96afa5a18f18617daa4427d55d0c36e26/manifestos/example_manifesto.yaml#L63) in the example_manifesto.yaml is the path to load the model but I don't find how to save the model into logs/sst_clean_ref_2. 

I'm pretty new to NLP so can you please tell me how to train or download the model?

Thanks,
Ziqi

**Comment by pmichel31415** [comment]
Hi Ziqi, glad you liked our paper.

this file corresponds to a fine-tuned version of the pre-trained model. This is the model from which the replacement embeddings are extracted. You can obtain this model by running `run_glue.py` with the appropriate parameters, then copying the resulting file to `logs/sst_clean_ref_2` (or updating your manifesto accordingly).

Hope that helps! Feel free to reopen the issue if you still have any problem
